### ISSUE TITLE
use external Clickhouse start failed

### ISSUE THREAD

**Issue by myoss** [SigNoz/opentelemetry-collector-contrib#1927]
**Describe the bug**

```bash
[root@wwww signoz]# kubectl -n signoz get pod signoz-otel-collector-6cdf8f5698-kf9ms  -o yaml
apiVersion: v1
kind: Pod
......
spec:
  containers:
  - command:
    - /otelcontribcol
    - --config=/conf/otel-collector-config.yaml
    env:
    - name: CLICKHOUSE_HOST
      value: 172.20.42.189
    - name: CLICKHOUSE_PORT
      value: "9013"
    - name: CLICKHOUSE_HTTP_PORT
      value: "8123"
    - name: CLICKHOUSE_CLUSTER
      value: cluster
    - name: CLICKHOUSE_DATABASE
      value: mydb
    - name: CLICKHOUSE_TRACE_DATABASE
      value: mydb
    - name: CLICKHOUSE_USER
      value: xxxxxx
    - name: CLICKHOUSE_PASSWORD
      value: xxxxxxxxx
    - name: CLICKHOUSE_SECURE
      value: "false"
    - name: CLICKHOUSE_VERIFY
      value: "false"
......

[root@wwww signoz]# kubectl -n signoz logs -f signoz-otel-collector-6cdf8f5698-kf9ms
022-07-20T11:05:38.088Z        error   clickhousetracesexporter/writer.go:101  Could not write a batch of spans        {"kind": "exporter", "name": "clickhousetraces", "error": "code: 81, message: Database signoz_traces doesn't exist"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/clickhousetracesexporter.(*SpanWriter).backgroundWriter
        /src/exporter/clickhousetracesexporter/writer.go:101
2022-07-20T11:05:48.097Z        error   clickhousetracesexporter/writer.go:101  Could not write a batch of spans        {"kind": "exporter", "name": "clickhousetraces", "error": "code: 81, message: Database signoz_traces doesn't exist"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/clickhousetracesexporter.(*SpanWriter).backgroundWriter
        /src/exporter/clickhousetracesexporter/writer.go:101
2022-07-20T11:05:58.098Z        error   clickhousetracesexporter/writer.go:101  Could not write a batch of spans        {"kind": "exporter", "name": "clickhousetraces", "error": "code: 81, message: Database signoz_traces doesn't exist"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/clickhousetracesexporter.(*SpanWriter).backgroundWriter
        /src/exporter/clickhousetracesexporter/writer.go:101
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x10636f2]
```

**What did you expect to see?**
use [signoz helm chart](https://github.com/SigNoz/charts/tree/main/charts/signoz) deploy in kubernetes

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
Version: `v0.10.0`, [36283d3](https://github.com/SigNoz/charts/commit/36283d3da7f19a612c63409c7071c2aa173b21c2)

**Comment by myoss** [comment]
@pranay01 @makeavish help, thanks.

**Comment by makeavish** [comment]
Did you upgrade from v0.7.5? If yes, did you follow migrations docs?
https://signoz.io/docs/operate/migration/upgrade-0.8.0/

**Comment by myoss** [comment]
not upgrade, new install. my database name is `mydb`, `clickhousetracesexporter/writer.go` is hard code database name `signoz_traces `

**Comment by makeavish** [comment]
Yeah, you can't change database.

**Comment by myoss** [comment]
why?
<img width="777" alt="Snipaste_2022-07-21_14-43-57" src="https://user-images.githubusercontent.com/6986459/180147632-e7d45e1f-a35b-489f-b4f3-f37960b9c994.png">

**Comment by ankitnayan** [comment]
@myoss I don't think these values are used at the backend. 

It would be good to create a separate issue for this. 

Any reason for not using the default databases? Is this a blocker?

**Comment by ankitnayan** [comment]
Does it work when using `signoz_traces` and `signoz_metrics` as db names?

**Comment by myoss** [comment]
my config, not effective
<img width="807" alt="image" src="https://user-images.githubusercontent.com/6986459/180151882-d415d9ee-d4f6-40b9-9ef6-96000ad9ad99.png">

**Comment by makeavish** [comment]
@myoss Please use `signoz_metrics` for database and `signoz_traces` for traceDatabase as db migrations are hard coded to `signoz_metrics` and `signoz_traces`.

**Comment by myoss** [comment]
oh my god, Bad design
