### ISSUE TITLE
database not update?

### ISSUE THREAD

**Issue by myoss** [SigNoz/opentelemetry-collector-contrib#772]
https://github.com/SigNoz/opentelemetry-collector-contrib/blob/90625b1cfb2d2e0c07a67def7eeba9203b09cdee/exporter/clickhouseexporter/clickhouse_factory.go#L119

When I deploy the test environment, use an external database and don't have permission to access the default `default database`, like this: 

<img width="534" alt="image" src="https://user-images.githubusercontent.com/6986459/168814976-f8ba1ce1-daf6-44e6-83f0-cd18c56f51f6.png">

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/6986459/168815632-094fb5e2-2f81-47e2-b47f-5d448e194cf2.png">

**Comment by pranay01** [comment]
@myoss Thanks for creating the issue. Were you trying to run the migration script to upgrade to v0.8.0? Which version of SigNoz are you currently on?

**Comment by myoss** [comment]
helm --namespace platform install my-release signoz/signoz --set clickhouse.enabled=false --set externalClickhouse.host=127.0.0.1 --set externalClickhouse.cluster=cluster --set externalClickhouse.user=demo --set externalClickhouse.password=mm

**Comment by makeavish** [comment]
@myoss That's because the DB migration creates a schema_migrations table in default db.
We should update the code to support custom db name from config.

**Comment by myoss** [comment]
same question: `http://signoz.example.com/api/v1/getSpanFilters`, custom db are not supported

<img width="1349" alt="image" src="https://user-images.githubusercontent.com/6986459/169189095-60f9991c-1b53-4554-88aa-52087af36bc2.png">

**Comment by makeavish** [comment]
@myoss DB migrations need access to the default database. 
This is a limitation of golang-migrate (https://github.com/golang-migrate/migrate/issues/690)
@prashant-shahi Please test if external DBs are supported.

**Comment by prashant-shahi** [comment]
Hey @myoss!

I was able to use `yandex/clickhouse-server:21.12.3.32` image as external clickhouse without any problem, where we use the default user.
It seems like permission issue in clickhouse for the specified user.

**Comment by makeavish** [comment]
Closing this as it's expected and user side access issue.
